import type { Opportunity, Thread, Community, RoadmapStep, SkillGap, FilterOption } from "./types";

export const opportunities: Opportunity[] = [
  {
    id: "1",
    title: "Google Data Analytics Professional Certificate",
    provider: "Google",
    type: "course",
    matchPercentage: 95,
    cost: "Free (Financial Aid Available)",
    duration: "6 Months",
    location: "Online",
    eligibility: "Beginner Friendly",
    mode: "online",
    verified: true,
    deadline: "2026-04-30",
    description:
      "Learn in-demand skills like SQL, R programming, Tableau, and data cleaning. This eight-course series prepares you for entry-level roles in data analytics.",
    whyRecommended: "Based on your interest in data-driven roles and your current skill set in Python.",
    skills: ["SQL", "R Programming", "Tableau", "Data Cleaning", "Data Visualization"],
    tags: ["AI & ML", "Data", "Beginner"],
  },
  {
    id: "2",
    title: "Undergraduate Scholarship Programme",
    provider: "Tata Trusts",
    type: "scholarship",
    matchPercentage: 92,
    cost: "Up to ₹2,00,000",
    duration: "1 Academic Year",
    location: "India",
    eligibility: "Currently enrolled UG students",
    mode: "offline",
    verified: true,
    deadline: "2026-03-15",
    description:
      "Financial assistance for undergraduate students pursuing higher education in India. Covers tuition, books, and living expenses for meritorious students.",
    whyRecommended: "You match the eligibility criteria and your academic profile is competitive.",
    skills: ["Academic Excellence", "Leadership", "Community Service"],
    tags: ["Scholarships", "Finance"],
  },
  {
    id: "3",
    title: "AI / ML Internship — Research Lab",
    provider: "Microsoft Research India",
    type: "internship",
    matchPercentage: 90,
    cost: "Stipend: ₹25,000/month",
    duration: "2 Months",
    location: "Remote",
    eligibility: "Students with ML fundamentals",
    mode: "remote",
    verified: true,
    deadline: "2026-02-28",
    description:
      "Work on cutting-edge AI research projects alongside Microsoft researchers. Gain hands-on experience with large-scale ML systems.",
    whyRecommended: "Your Python and ML skills align with the core requirements.",
    skills: ["Python", "Machine Learning", "PyTorch", "Research Methodology"],
    tags: ["AI & ML", "Research", "Remote"],
  },
  {
    id: "4",
    title: "Junior Software Developer",
    provider: "Infosys",
    type: "job",
    matchPercentage: 88,
    cost: "₹4–7 LPA",
    duration: "Full-time",
    location: "Bangalore / Hybrid",
    eligibility: "Fresh graduates (BCA, B.Tech)",
    mode: "hybrid",
    verified: true,
    deadline: "2026-05-15",
    description:
      "Join Infosys as a Junior Software Developer working on enterprise applications. Excellent training program for fresh graduates.",
    whyRecommended: "Your programming skills and educational background match well.",
    skills: ["Java", "JavaScript", "SQL", "Git", "Agile"],
    tags: ["Jobs", "Development"],
  },
  {
    id: "5",
    title: "AWS Cloud Practitioner Certification",
    provider: "Amazon Web Services",
    type: "course",
    matchPercentage: 87,
    cost: "₹7,500 (Exam Fee)",
    duration: "2 Months",
    location: "Online",
    eligibility: "Beginner Friendly",
    mode: "online",
    verified: true,
    deadline: "2026-06-30",
    description:
      "Gain foundational knowledge of AWS Cloud services and cloud concepts. Ideal starting point for cloud computing careers.",
    whyRecommended: "Cloud skills are in high demand and complement your development background.",
    skills: ["AWS Services", "Cloud Architecture", "Security", "Pricing Models"],
    tags: ["Cloud", "Certification"],
  },
  {
    id: "6",
    title: "Smart India Hackathon 2026",
    provider: "NASSCOM",
    type: "internship",
    matchPercentage: 85,
    cost: "Free",
    duration: "2 Weeks",
    location: "Pan India",
    eligibility: "UG/PG students",
    mode: "offline",
    verified: true,
    deadline: "2026-03-20",
    description:
      "India's largest hackathon. Solve real-world problems and compete for prizes worth ₹1 Crore+. Build your network and portfolio.",
    whyRecommended: "Great opportunity to apply your skills and build projects.",
    skills: ["Problem Solving", "Teamwork", "Prototype Development"],
    tags: ["Hackathon", "Innovation"],
  },
  {
    id: "7",
    title: "Digital India Cybersecurity Internship",
    provider: "NASSCOM",
    type: "internship",
    matchPercentage: 82,
    cost: "Stipend: ₹15,000/month",
    duration: "3 Months",
    location: "Hybrid",
    eligibility: "Students with basic networking knowledge",
    mode: "hybrid",
    verified: true,
    deadline: "2026-04-10",
    description:
      "Work on real cybersecurity projects under the Digital India initiative. Learn ethical hacking, network security, and compliance.",
    whyRecommended: "Expands your skill set into the growing cybersecurity domain.",
    skills: ["Networking", "Ethical Hacking", "Security Auditing"],
    tags: ["Cybersecurity", "Government"],
  },
  {
    id: "8",
    title: "Full-Stack Web Development Bootcamp",
    provider: "Coursera × Meta",
    type: "course",
    matchPercentage: 86,
    cost: "Free (Audit) / ₹3,500/mo (Certificate)",
    duration: "4 Months",
    location: "Online",
    eligibility: "Some programming experience",
    mode: "online",
    verified: true,
    deadline: "2026-06-01",
    description:
      "Master React, Node.js, and modern web development practices from Meta engineers. Build a professional portfolio of projects.",
    whyRecommended: "Strengthen your web development skills with industry-standard tools.",
    skills: ["React", "Node.js", "JavaScript", "MongoDB", "REST APIs"],
    tags: ["Web Dev", "Full-Stack"],
  },
];

export const threadPreviews = [
  {
    title: "Has anyone applied for this AI internship?",
    author: "priya_dev",
    upvotes: 24,
    comments: 12,
    tags: ["Internship", "AI"],
  },
  {
    title: "Best roadmap for becoming an ML Engineer?",
    author: "rahul_ml",
    upvotes: 89,
    comments: 34,
    tags: ["Career", "ML"],
  },
  {
    title: "Free certifications that are actually worth it",
    author: "ananya_k",
    upvotes: 156,
    comments: 47,
    tags: ["Certification", "Career"],
  },
  {
    title: "How I got my first internship at a startup",
    author: "vikram_s",
    upvotes: 67,
    comments: 23,
    tags: ["Internship", "Tips"],
  },
];

export const threads: Thread[] = [
  {
    id: "1",
    title: "Has anyone applied for this AI internship at MSR?",
    author: "priya_dev",
    authorAvatar: undefined,
    community: "AI & Machine Learning",
    upvotes: 24,
    comments: [
      {
        id: "c1",
        author: "rahul_ml",
        authorAvatar: undefined,
        content: "Applied last week! The selection process includes a coding test and a research discussion. Took about 2 weeks to hear back.",
        upvotes: 8,
        createdAt: "2 days ago",
        replies: [
          {
            id: "c1r1",
            author: "priya_dev",
            content: "Thanks! Did you need prior research experience?",
            upvotes: 2,
            createdAt: "1 day ago",
          },
        ],
      },
      {
        id: "c2",
        author: "ananya_k",
        content: "I got selected! It's a great experience. The mentors are very supportive.",
        upvotes: 15,
        createdAt: "1 day ago",
      },
    ],
    tags: ["Internship", "AI", "Microsoft"],
    createdAt: "3 days ago",
    preview: "Looking for peers who've gone through the MSR internship process...",
  },
  {
    id: "2",
    title: "Best roadmap for becoming an ML Engineer in 2026?",
    author: "rahul_ml",
    community: "AI & Machine Learning",
    upvotes: 89,
    comments: [
      {
        id: "c3",
        author: "deepak_ai",
        content: "Start with Andrew Ng's courses, then move to fast.ai. After that, focus on one domain and build projects.",
        upvotes: 32,
        createdAt: "5 days ago",
      },
    ],
    tags: ["Career", "ML", "Roadmap"],
    createdAt: "5 days ago",
    preview: "What's the ideal learning path for someone starting from scratch?",
  },
  {
    id: "3",
    title: "Free certifications that are actually worth it in 2026",
    author: "ananya_k",
    community: "Web Development",
    upvotes: 156,
    comments: [],
    tags: ["Certification", "Free"],
    createdAt: "1 week ago",
    preview: "I've compiled a list of certifications that employers actually value...",
  },
  {
    id: "4",
    title: "Scholarships for BCA students — Megathread",
    author: "mod_team",
    community: "Scholarships",
    upvotes: 213,
    comments: [],
    tags: ["Scholarship", "BCA", "Pinned"],
    createdAt: "2 weeks ago",
    preview: "A comprehensive list of scholarships available for BCA students in India...",
  },
  {
    id: "5",
    title: "How I built a portfolio that landed me 3 internship offers",
    author: "vikram_s",
    community: "Web Development",
    upvotes: 67,
    comments: [],
    tags: ["Portfolio", "Career", "Tips"],
    createdAt: "4 days ago",
    preview: "Sharing my experience and the projects that made a difference...",
  },
  {
    id: "6",
    title: "Is cybersecurity a good career path for BCA graduates?",
    author: "neha_sec",
    community: "Cybersecurity",
    upvotes: 45,
    comments: [],
    tags: ["Career", "Cybersecurity"],
    createdAt: "6 days ago",
    preview: "Considering a switch from web dev to cybersecurity...",
  },
];

export const communities: Community[] = [
  {
    id: "1",
    name: "AI & Machine Learning",
    memberCount: 12400,
    description: "Discuss ML, deep learning, and AI research. Share projects and learn together.",
  },
  {
    id: "2",
    name: "Web Development",
    memberCount: 8900,
    description: "Frontend, backend, and full-stack development discussions.",
  },
  {
    id: "3",
    name: "Cybersecurity",
    memberCount: 5600,
    description: "Ethical hacking, network security, and career guidance.",
  },
  {
    id: "4",
    name: "Scholarships",
    memberCount: 15200,
    description: "Find and discuss scholarships for Indian students.",
  },
  {
    id: "5",
    name: "Internships",
    memberCount: 11800,
    description: "Internship opportunities, applications, and experiences.",
  },
  {
    id: "6",
    name: "BCA Students",
    memberCount: 7300,
    description: "Resources, guidance, and community for BCA students.",
  },
];

export const roadmapSteps: RoadmapStep[] = [
  { id: "1", title: "Python", status: "completed", description: "Core syntax, data structures, OOP" },
  { id: "2", title: "SQL", status: "completed", description: "Queries, joins, database design" },
  { id: "3", title: "Statistics", status: "in-progress", description: "Probability, distributions, hypothesis testing" },
  { id: "4", title: "Machine Learning", status: "locked", resource: "Google ML Crash Course" },
  { id: "5", title: "Projects", status: "locked", description: "Build 3 portfolio projects" },
  { id: "6", title: "Internship", status: "locked", description: "Apply for ML internships" },
  { id: "7", title: "AI Engineer", status: "recommended", description: "Full-time role" },
];

export const skillGaps: SkillGap[] = [
  { skill: "Python", progress: 100, completed: true },
  { skill: "SQL", progress: 100, completed: true },
  { skill: "Machine Learning", progress: 60, completed: false },
  { skill: "Deep Learning", progress: 20, completed: false },
  { skill: "Statistics", progress: 45, completed: false },
  { skill: "Data Visualization", progress: 70, completed: false },
];

export const filters: FilterOption[] = [
  { id: "type", label: "Type", options: ["All", "Course", "Scholarship", "Internship", "Job"] },
  { id: "cost", label: "Cost", options: ["All", "Free", "Under ₹5,000", "Under ₹10,000", "Paid"] },
  { id: "location", label: "Location", options: ["All", "Online", "Hybrid", "Remote", "On-site"] },
  { id: "duration", label: "Duration", options: ["All", "Under 1 Month", "1-3 Months", "3-6 Months", "6+ Months"] },
  { id: "mode", label: "Mode", options: ["All", "Online", "Offline", "Hybrid", "Remote"] },
];

export const trustedSources = [
  "Google",
  "Microsoft",
  "Coursera",
  "AWS",
  "NASSCOM",
  "Digital India",
];

export const quickSearchTags = [
  "AI & ML",
  "Scholarships",
  "Internships",
  "Free Courses",
];
