# Generated by Django 4.2.16 on 2026-09-05 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('type', models.CharField(choices=[('Internship', 'Internship'), ('Placement', 'Placement'), ('Part-time', 'Part-time')], default='Internship', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('openings', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('work_arrangement', models.CharField(choices=[('On-site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='On-site', max_length=12)),
                ('duration', models.CharField(blank=True, default='', max_length=80)),
                ('stipend', models.CharField(blank=True, default='', max_length=80)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('eligibility_qualification', models.CharField(blank=True, default='', max_length=240)),
                ('eligibility_courses', models.JSONField(blank=True, default=list)),
                ('eligibility_experience', models.CharField(blank=True, default='', max_length=160)),
                ('eligibility_other', models.TextField(blank=True, default='')),
                ('registration_requirements', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'draft'), ('active', 'active'), ('paused', 'paused'), ('closed', 'closed'), ('closing', 'closing')], default='active', max_length=10)),
                ('blind_shortlisting', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_opportunity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratee_type', models.CharField(choices=[('student', 'student'), ('industry', 'industry')], max_length=12)),
                ('score', models.PositiveSmallIntegerField(default=5)),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='marketplace.opportunity')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_rating',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunitySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.CharField(choices=[('essential', 'essential'), ('preferred', 'preferred')], default='essential', max_length=10)),
                ('min_proficiency', models.PositiveIntegerField(default=60)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='marketplace.opportunity')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities_needing', to='catalog.skill')),
            ],
            options={
                'db_table': 'marketplace_opportunity_skill',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('applied', 'applied'), ('shortlisted', 'shortlisted'), ('interviewed', 'interviewed'), ('offered', 'offered'), ('joined', 'joined'), ('rejected', 'rejected')], default='applied', max_length=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='marketplace.opportunity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'marketplace_application',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='opportunityskill',
            constraint=models.UniqueConstraint(fields=('opportunity', 'skill'), name='uniq_opportunity_skill'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('opportunity', 'student'), name='uniq_application_opportunity_student'),
        ),
    ]
