# Generated by Django 4.2.16 on 2026-09-05 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Internship', 'Internship'), ('Placement', 'Placement')], default='Internship', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=80)),
                ('stipend', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('offered', 'offered')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='catalog.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'governance_placement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('type', models.CharField(choices=[('Placement', 'Placement'), ('Skill Development', 'Skill Development'), ('Internship', 'Internship'), ('Readiness', 'Readiness'), ('Industry Engagement', 'Industry Engagement'), ('Anomaly', 'Anomaly')], default='Placement', max_length=24)),
                ('period', models.CharField(blank=True, default='', max_length=120)),
                ('generated_at', models.DateField(auto_now_add=True)),
                ('departments', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('key_findings', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ready', 'ready'), ('generating', 'generating')], default='ready', max_length=12)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='catalog.institution')),
            ],
            options={
                'db_table': 'governance_institutional_report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentSkillMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_demand', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('curriculum_coverage', models.PositiveIntegerField(default=0)),
                ('student_proficiency', models.PositiveIntegerField(default=0)),
                ('gap_severity', models.CharField(choices=[('Critical', 'Critical'), ('Moderate', 'Moderate'), ('Acceptable', 'Acceptable')], default='Moderate', max_length=12)),
                ('trend', models.CharField(choices=[('up', 'up'), ('up-strong', 'up-strong'), ('stable', 'stable'), ('down', 'down')], default='stable', max_length=10)),
                ('students_with_gap', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_metrics', to='catalog.department')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_metrics', to='catalog.skill')),
            ],
            options={
                'db_table': 'governance_department_skill_metric',
                'ordering': ['skill__name'],
            },
        ),
        migrations.CreateModel(
            name='DemandTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='2025-09', max_length=7)),
                ('direction', models.CharField(choices=[('up', 'up'), ('up-strong', 'up-strong'), ('stable', 'stable'), ('down', 'down')], default='stable', max_length=10)),
                ('demand_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('change_percent', models.IntegerField(default=0)),
                ('openings', models.PositiveIntegerField(default=0)),
                ('period_label', models.CharField(blank=True, default='Last 6 months', max_length=40)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_trends', to='catalog.skill')),
            ],
            options={
                'db_table': 'governance_demand_trend',
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateField(auto_now_add=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('avg_readiness', models.PositiveIntegerField(default=0)),
                ('readiness_distribution', models.JSONField(default=dict)),
                ('top_gaps', models.JSONField(default=list)),
                ('coverage_gaps', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('insights', models.JSONField(default=list)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_reports', to='catalog.department')),
            ],
            options={
                'db_table': 'governance_curriculum_report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Duplicate Record', 'Duplicate Record'), ('Inconsistent Data', 'Inconsistent Data'), ('Statistical Outlier', 'Statistical Outlier'), ('Unusual Pattern', 'Unusual Pattern')], default='Duplicate Record', max_length=24)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('flagged', 'flagged'), ('reviewing', 'reviewing'), ('resolved', 'resolved'), ('escalated', 'escalated')], default='flagged', max_length=10)),
                ('evidence', models.TextField(blank=True, default='')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_anomalies', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'governance_anomaly_flag',
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicianOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FDP', 'FDP'), ('Industrial Training', 'Industrial Training'), ('Consultancy', 'Consultancy'), ('Research Collaboration', 'Research Collaboration')], default='FDP', max_length=28)),
                ('title', models.CharField(max_length=240)),
                ('organizer', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('duration', models.CharField(blank=True, default='', max_length=80)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('skills_relevant', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'open'), ('closing', 'closing'), ('closed', 'closed')], default='open', max_length=10)),
                ('interested', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_academic_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'governance_academician_opportunity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='departmentskillmetric',
            constraint=models.UniqueConstraint(fields=('department', 'skill'), name='uniq_dept_skill_metric'),
        ),
        migrations.AddConstraint(
            model_name='demandtrend',
            constraint=models.UniqueConstraint(fields=('skill', 'month'), name='uniq_skill_month'),
        ),
    ]
