# Generated by Django 4.2.16 on 2026-09-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('initials', models.CharField(blank=True, default='', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('org_type', models.CharField(blank=True, default='Government Institute', max_length=120)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('verified', models.BooleanField(default=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_faculty', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'catalog_institution',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomy_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Domain', 'Domain'), ('Research', 'Research'), ('Communication', 'Communication'), ('Management', 'Management')], default='Domain', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('industry_demand', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
            ],
            options={
                'db_table': 'catalog_skill',
            },
        ),
        migrations.CreateModel(
            name='TargetRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='Clinical Research', max_length=120)),
            ],
            options={
                'db_table': 'catalog_target_role',
            },
        ),
        migrations.CreateModel(
            name='TargetRoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('essential', 'essential'), ('preferred', 'preferred')], default='essential', max_length=12)),
                ('min_proficiency', models.PositiveIntegerField(default=60)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_in_roles', to='catalog.skill')),
                ('target_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='catalog.targetrole')),
            ],
            options={
                'db_table': 'catalog_target_role_skill',
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Course', 'Course'), ('Workshop', 'Workshop'), ('Learning path', 'Learning path'), ('Certification', 'Certification'), ('Project', 'Project')], default='Course', max_length=24)),
                ('title', models.CharField(max_length=240)),
                ('provider', models.CharField(blank=True, default='', max_length=160)),
                ('duration', models.CharField(blank=True, default='', max_length=80)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('url', models.URLField(blank=True, default='')),
                ('why', models.TextField(blank=True, default='')),
                ('closes_gap_name', models.CharField(blank=True, default='', max_length=160)),
                ('skills_improved', models.JSONField(blank=True, default=list)),
                ('boost_points', models.PositiveIntegerField(default=15)),
                ('description', models.TextField(blank=True, default='')),
                ('closes_gap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='catalog.skill')),
            ],
            options={
                'db_table': 'catalog_learning_resource',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.CharField(blank=True, default='', max_length=30)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='catalog.institution')),
            ],
            options={
                'db_table': 'catalog_department',
            },
        ),
        migrations.AddConstraint(
            model_name='targetroleskill',
            constraint=models.UniqueConstraint(fields=('target_role', 'skill'), name='uniq_role_skill'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='uniq_dept_per_institution'),
        ),
    ]
