# Generated by Django 4.2.16 on 2026-09-05 07:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('student', 'Student'), ('industry', 'Industry'), ('academician', 'Academician'), ('institution_admin', 'Institution Admin'), ('admin', 'Platform Admin')], db_index=True, default='student', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, default='', max_length=40)),
                ('institution_name', models.CharField(blank=True, default='', max_length=200)),
                ('department_name', models.CharField(blank=True, default='', max_length=120)),
                ('course', models.CharField(blank=True, default='BAMS', max_length=120)),
                ('year', models.CharField(blank=True, default='3rd Year', max_length=40)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('bio', models.TextField(blank=True, default='')),
                ('career_interests', models.JSONField(blank=True, default=list)),
                ('target_role_name', models.CharField(blank=True, default='', max_length=160)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_members', to='catalog.department')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='catalog.institution')),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_targeting', to='catalog.targetrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_student_profile',
            },
        ),
        migrations.CreateModel(
            name='InstitutionAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='catalog.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institution_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_institution_admin_profile',
            },
        ),
        migrations.CreateModel(
            name='IndustryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('domain', models.CharField(blank=True, default='', max_length=160)),
                ('org_type', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('website', models.URLField(blank=True, default='')),
                ('company_email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('contact_person', models.CharField(blank=True, default='', max_length=160)),
                ('verified', models.BooleanField(default=False)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, default='', max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industry_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_industry_profile',
            },
        ),
        migrations.CreateModel(
            name='AcademicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, default='', max_length=160)),
                ('institution_name', models.CharField(blank=True, default='', max_length=200)),
                ('department_name', models.CharField(blank=True, default='', max_length=120)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('research_interests', models.JSONField(blank=True, default=list)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True, default='')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_members', to='catalog.department')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty', to='catalog.institution')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_academician_profile',
            },
        ),
    ]
