# Generated by Django 4.2.16 on 2026-09-05 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('kind', models.CharField(choices=[('Certificate', 'Certificate'), ('Project', 'Project'), ('Transcript', 'Transcript'), ('Internship', 'Internship'), ('Publication', 'Publication'), ('Portfolio', 'Portfolio'), ('Log', 'Log')], default='Certificate', max_length=24)),
                ('issuer', models.CharField(blank=True, default='', max_length=200)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('verified', 'verified'), ('processing', 'processing'), ('needs review', 'needs review')], default='processing', max_length=16)),
                ('file_url', models.URLField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credentials_evidence_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=16)),
                ('estimated_duration', models.CharField(blank=True, default='', max_length=80)),
                ('deliverables', models.JSONField(blank=True, default=list)),
                ('verification_criteria', models.JSONField(blank=True, default=list)),
                ('target_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_recommendations', to='catalog.skill')),
            ],
            options={
                'db_table': 'credentials_project_recommendation',
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('type', models.CharField(choices=[('Internship', 'Internship'), ('Project', 'Project'), ('Certificate', 'Certificate'), ('Outcome', 'Outcome'), ('Skill Evidence', 'Skill Evidence')], default='Project', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('skills_claimed', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('flagged', 'flagged'), ('changes-requested', 'changes-requested')], default='pending', max_length=18)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='credentials.evidenceitem')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credentials_verification_request',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('evidence', 'evidence'), ('self-declared', 'self-declared')], default='self-declared', max_length=14)),
                ('confidence', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_claims', to='credentials.evidenceitem')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='catalog.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credentials_skill_claim',
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not submitted', 'not submitted'), ('pending review', 'pending review'), ('verified', 'verified'), ('needs revision', 'needs revision')], default='not submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('review_comment', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='credentials.projectrecommendation')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_projects', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credentials_project_submission',
            },
        ),
        migrations.AddConstraint(
            model_name='skillclaim',
            constraint=models.UniqueConstraint(fields=('student', 'skill'), name='uniq_student_skill'),
        ),
        migrations.AddConstraint(
            model_name='projectsubmission',
            constraint=models.UniqueConstraint(fields=('student', 'project'), name='uniq_student_project_submission'),
        ),
    ]
